name: Build and Push APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Commit and Push APK
        run: |
          mkdir -p apk
          cp build/app/outputs/flutter-apk/app-release.apk apk/KCET_PATROL_APP.apk
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add apk/KCET_PATROL_APP.apk
          git commit -m "chore: auto-build and push latest APK" || echo "No changes to commit"
          git push origin main
